name: Build animation

on:
  push:
    branches:
      - self-hosted-runner
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies - testing this instead of actions/cache

    - name: Install pytoon
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install pytoon 
    
    - name: Install moviepy and audioop
      run: |
        pip install moviepy==1.0.3 audioop-lts==0.2.1

    - name: Install dependencies
      run: |
        python -m nltk.downloader punkt averaged_perceptron_tagger averaged_perceptron_tagger_eng cmudict words

    - name: Run tests
      run: |
        python main.py


    - name: Upload animation to github actions results
      uses: actions/upload-artifact@v4
      with:
        name: animation.mp4
        path: animation.mp4